[project]
name = "LightingControl"
version = "1.0.0"
description = "Control multiple lights using Shelly smart switches"
readme = "README.md"
requires-python = ">=3.13"
service_name="LightingControl"
launch_path="src/main.py"
dependencies = [
    "astral>=3.2",
    "pytz>=2025.2",
    "sc-utility>=2.4.8",
]
